config/routes.rb
Rails.application.routes.draw do
  root 'dashboard#index'

  resources :trainees

end

app/models/trainee.rb
class Trainee < ActiveRecord::Base
  validates :first_name, :last_name, :birthday, :year, :email, :phone, :room, :suse_login, :github, :trello, :description, :image, presence: :true
  validates :email, email: true
  validates :year, inclusion: 1..3

  mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :set_locale

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end
end

app/controllers/trainees_controller.rb
class TraineesController < ApplicationController
  def index
    @trainees = Trainee.where(year: params[:year]).decorate

    if request.xhr?
      render "update_table"
    end
  end

  def new
    @trainee = Trainee.new
  end

  def create
    @trainee = Trainee.new(trainee_params)
    if @trainee.save
      redirect_to action: "index", year: @trainee.year
    else
      flash[:error] = "Error adding trainee. Please check if you filled in all fields correctly and entered a valid email address!"
      render :new
    end
  end

  def edit
    @trainee = Trainee.find(params[:id])
  end

  def update
    @trainee = Trainee.find(params[:id])
    @trainee.update(trainee_params)
    redirect_to action: "index", year: @trainee.year
  end

  protected

  def trainee_params
    params.require(:trainee).permit(:first_name, :last_name, :birthday, :year, :email, :phone, :room, :suse_login, :github, :trello, :description, :image, :remote_image_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/index.html.erb
<div class="jumbotron">
  <h1>Welcome to the SUSE Trainee Dashboard!</h1>
  <h3>Please be patient, still getting in shape here.</h3>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>TraineeDashboard</title>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
  <div id="wrapper">
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">SUSE Trainee Dashboard</a>
      </div>
        <div class="collapse navbar-collapse navbar-ex1-collapse">
          <ul class="nav navbar-nav side-nav">
            <li>
              <a href="/"><i class="fa fa-fw fa-dashboard"></i>  Home</a>
            </li>
            <li>
              <a href="javascript:;" data-toggle="collapse" data-target="#demo"><i class="fa fa-fw fa-users"></i> Trainees <i class="fa fa-fw fa-caret-down"></i></a>
              <ul id="demo" class="collapse">
                <li>
                  <%= link_to '1st year', trainees_path(year: 1) %>
                </li>
                <li>
                  <%= link_to '2nd year', trainees_path(year: 2) %>
                </li>
                <li>
                  <%= link_to '3rd year', trainees_path(year: 3) %>
                </li>
              </ul>
            </li>
          </ul>
      </div>
          <!-- /.navbar-collapse -->
      </nav>

      <div id="page-wrapper">
        <div class="container-fluid">
          <div class="row">
          <div class="col-lg-12">
            <%= yield %>
          </div>
          <!-- /.row -->
        </div>
        <!-- /.container-fluid -->
        </div>
        <!-- /#page-wrapper -->
      </div>
    <!-- /#wrapper -->
  <div class="footer navbar-fixed-bottom">
    <div class="container">
    <p class="text-muted">Made with love for SUSE's trainees. がんばろう!! </p>
    </div>
  </div>
</body>
</html>

app/views/trainees/_trainee.html.erb
<tr>
<div class="panel panel-success">
<div class="panel-heading">
	<div class="row">
		<div class="col-xs-4 col-sm-6">
			<h4 align="center"><%= image_tag trainee.image_url(:thumb).to_s %></h4>
		</div>
		<div class="col-xs-4 col-sm-6">
		<div class="panel panel-default">
			<h4 align="center">Name: <%= trainee.full_name %></h4>
			<h5 align="center">Birthday: <%= l trainee.birthday, format: :long %></h5>
			<h5 align="center">Year: <%= trainee.year %></h5>
			<h5 align="center">eMail: <%= trainee.email %></h5>
			<h5 align="center">Phone: <%= trainee.phone %></h5>
			<h5 align="center">Room: <%= trainee.room %></h5>
			<h5 align="center">Login @ Suse: <%= trainee.suse_login %></h5>
			<h5 align="center">GitHub: <%= trainee.github %></h5>
			<h5 align="center">Trello: <%= trainee.trello %></h5>
			<h5 align="center">Description: <%= trainee.description %></h5>
		</div>
		</div>
	</div>
	</div>
	<div class="panel-footer"><%= link_to 'Edit...', edit_trainee_path(trainee) %>
	</div>
</div>
</tr>

app/views/trainees/edit.html.erb
<div class="row">
	<div class="col-md-2"></div>

	<div class="col-md-8">

		<div class="panel panel-success">
			<div class="panel-heading">Edit your stuff!</div>

		<div class="panel-body">
			<%= form_for @trainee, :html => {:class => 'form-horizontal', :multipart => true }, url: trainee_url do |f| %>
      <div class="form-group">
        <%= f.label :first_name, :class => "control-label col-md-3" %>
        <div class="col-md-7">
          <%= f.text_field :first_name, :class => "form-control", required: true %>
        </div>
        <div class="col-md-offset-3"></div>
      </div>

      <div class="form-group">
        <%= f.label :last_name, :class => "control-label col-md-3" %>
        <div class="col-md-7">
          <%= f.text_field :last_name, :class => "form-control", required: true %>
        </div>
        <div class="col-md-offset-3"></div>
      </div>

      <div class="form-group">
        <%= f.label :birthday, :class => "control-label col-md-3" %>
        <div class="col-md-7">
          <%= f.date_field :birthday, :class => "form-control", required: true %>
        </div>
        <div class="col-md-offset-3"></div>
      </div>

      <div class="form-group">
        <%= f.label :year, :class => "control-label col-md-3" %>
        <div class="col-md-7">
          <%= f.text_field :year, :class => "form-control", required: true %>
        </div>
        <div class="col-md-offset-3"></div>
      </div>

      <div class="form-group">
        <%= f.label :email, :class => "control-label col-md-3" %>
        <div class="col-md-7">
          <%= f.text_field :email, :class => "form-control", required: true %>
        </div>
        <div class="col-md-offset-3"></div>
      </div>

      <div class="form-group">
        <%= f.label :phone, :class => "control-label col-md-3" %>
        <div class="col-md-7">
          <%= f.text_field :phone, :class => "form-control", required: true %>
        </div>
        <div class="col-md-offset-3"></div>
      </div>

      <div class="form-group">
        <%= f.label :room, :class => "control-label col-md-3" %>
        <div class="col-md-7">
          <%= f.text_field :room, :class => "form-control", required: true %>
        </div>
        <div class="col-md-offset-3"></div>
      </div>

      <div class="form-group">
        <%= f.label :suse_login, :class => "control-label col-md-3" %>
        <div class="col-md-7">
          <%= f.text_field :suse_login, :class => "form-control", required: true %>
        </div>
        <div class="col-md-offset-3"></div>
      </div>

      <div class="form-group">
        <%= f.label :github, :class => "control-label col-md-3" %>
        <div class="col-md-7">
          <%= f.text_field :github, :class => "form-control", required: true %>
        </div>
        <div class="col-md-offset-3"></div>
      </div>

      <div class="form-group">
        <%= f.label :trello, :class => "control-label col-md-3" %>
        <div class="col-md-7">
          <%= f.text_field :trello, :class => "form-control", required: true %>
        </div>
        <div class="col-md-offset-3"></div>
      </div>

      <div class="form-group">
        <%= f.label :description, :class => "control-label col-md-3" %>
        <div class="col-md-7">
          <%= f.text_area :description, :class => "form-control", :rows => "5", :placeholder => "Please tell us more about yourself (e.g. what you did before joining SUSE etc)!", required: true %>
        </div>
        <div class="col-md-offset-3"></div>
      </div>

      <div class="form-group">
        <%= f.label :image, :class => "control-label col-md-3" %>
        <div class="col-md-7">
          <%= f.file_field :image %>
        </div>
        <div class="col-md-7">
          <%= f.label :remote_image_url, "or image URL:" %><br>
          <%= f.text_field :remote_image_url %>
        </div>
        <div class="col-md-offset-3"></div>
      </div>

      <div class="form-group">
        <div class="col-md-offset-3 col-md-10">
          <%= link_to 'Cancel', :back, :class => "btn btn-default" %>
          <%= f.submit 'Update', method: :patch, :class => "btn btn-success" %>
        </div>
      </div>
		<% end %>
		</div>
		</div>
	</div>
</div>

app/views/trainees/index.html.erb
<div class="row">
	<div class="col-md-5">
	<div class="panel panel-default">
		<div class="panel-body">
			<h2>The trainee elite of SUSE :D</h2>
			<p>
			<p><%= link_to 'Add yourself to our glorious list!', new_trainee_path %></p>
		</div>
	</div>
	</div>
	<div class="col-md-7">
	<% if @trainees %>
		<table class="table">
			<tbody id="trainees">
				<%= render @trainees %>
			</tbody>
		</table>
		<% else %>
			<div class="alert alert-success" role="alert">
				No trainees yet!
			</div>
		<% end %>
	</div>
</div>

app/views/trainees/new.html.erb
<div class="row">
	<div class="col-md-2"></div>

	<div class="col-md-8">
    <% if flash[:error] %>
    <div class="alert alert-warning alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <%= flash[:error] %>
    </div>
    <% end %>
    
		<div class="panel panel-success">
			<div class="panel-heading">Add yourself to the list!</div>

		<div class="panel-body">
			<%= form_for @trainee, html: {:class => 'form-horizontal'}, url: trainees_url do |f| %>

      <div class="form-group">
        <%= f.label :first_name, :class => "control-label col-md-3" %>
        <div class="col-md-7">
          <%= f.text_field :first_name, :class => "form-control", required: true %>
        </div>
        <div class="col-md-offset-3"></div>
      </div>

      <div class="form-group">
        <%= f.label :last_name, :class => "control-label col-md-3" %>
        <div class="col-md-7">
          <%= f.text_field :last_name, :class => "form-control", required: true %>
        </div>
        <div class="col-md-offset-3"></div>
      </div>

      <div class="form-group">
        <%= f.label :birthday, :class => "control-label col-md-3" %>
        <div class="col-md-7">
          <%= f.date_field :birthday, :class => "form-control", required: true %>
        </div>
        <div class="col-md-offset-3"></div>
      </div>

      <div class="form-group">
        <%= f.label :year, :class => "control-label col-md-3" %>
        <div class="col-md-7">
          <%= f.text_field :year, :class => "form-control", :placeholder => "1, 2 or 3", required: true %>
        </div>
        <div class="col-md-offset-3"></div>
      </div>

      <div class="form-group">
        <%= f.label :email, :class => "control-label col-md-3" %>
        <div class="col-md-7">
          <%= f.email_field :email, :class => "form-control", :placeholder => "e.g. geeko@suse.com", required: true %>
        </div>
        <div class="col-md-offset-3"></div>
      </div>

      <div class="form-group">
        <%= f.label :phone, :class => "control-label col-md-3" %>
        <div class="col-md-7">
          <%= f.text_field :phone, :class => "form-control", required: true %>
        </div>
        <div class="col-md-offset-3"></div>
      </div>

      <div class="form-group">
        <%= f.label :room, :class => "control-label col-md-3" %>
        <div class="col-md-7">
          <%= f.text_field :room, :class => "form-control", required: true %>
        </div>
        <div class="col-md-offset-3"></div>
      </div>

      <div class="form-group">
        <%= f.label :suse_login, :class => "control-label col-md-3" %>
        <div class="col-md-7">
          <%= f.text_field :suse_login, :class => "form-control", required: true %>
        </div>
        <div class="col-md-offset-3"></div>
      </div>

      <div class="form-group">
        <%= f.label :github, :class => "control-label col-md-3" %>
        <div class="col-md-7">
          <%= f.text_field :github, :class => "form-control", required: true %>
        </div>
        <div class="col-md-offset-3"></div>
      </div>

      <div class="form-group">
        <%= f.label :trello, :class => "control-label col-md-3" %>
        <div class="col-md-7">
          <%= f.text_field :trello, :class => "form-control", required: true %>
        </div>
        <div class="col-md-offset-3"></div>
      </div>

      <div class="form-group">
        <%= f.label :description, :class => "control-label col-md-3" %>
        <div class="col-md-7">
          <%= f.text_area :description, :class => "form-control", :rows => "5", :placeholder => "Please tell us more about yourself (e.g. what you did before joining SUSE etc)!" %>
        </div>
        <div class="col-md-offset-3"></div>
      </div>

      <div class="form-group">
        <%= f.label :image, :class => "control-label col-md-3" %>
        <div class="col-md-7">
          <%= f.file_field :image %>
        </div>
        <div class="col-md-7">
          <%= f.label :remote_image_url, "or image URL:" %><br>
          <%= f.text_field :remote_image_url %>
        </div>
        <div class="col-md-offset-3"></div>
      </div>

      <div class="form-group">
        <div class="col-md-offset-3 col-md-10">
          <%= link_to 'Cancel', :back, :class => "btn btn-default" %>
          <%= f.submit 'Add', :class => "btn btn-success" %>
        </div>
      </div>
		<% end %>
		</div>
		</div>
	</div>
</div>

app/views/trainees/update_table.js.erb
$('#trainees').html('<%= j render(@trainees) %>');